# Generated by Django 3.0.7 on 2022-12-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_classassignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='classassignments',
            name='file_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
